project:
  type: website

website:
  title: "prodatphil"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
output-dir: docs

