---
format: html
editor: visual
---
# Studies in Logical Theory

By **John Dewey** (1903)

------------------------------------------------------------------------

Bacon's dictum regarding the proneness of the mind, in explanation, towards unity and simplicity, at no matter what sacrifice of material, has found no more striking exemplification than that offered in the fortunes of psychology. The least developed of the sciences, for a hundred years it has borne in its presentations the air of the one most completely finished. The infinite detail and complexity of the simplest psychical life, its interweavings with the physical organism, with the life of others in the social organism,-- created no special difficulty; and in a book like James Mill's *Analysis* we find every mental phenomenon not only explained, but explained by reference to one principle. That rich and colored experience, never the same in two nations, in two individuals, in two moments of the same life,-- whose thoughts, desires, fears, and hopes have furnished the material for the ever-developing literature of the ages, for a Homer and a Chaucer, a Sophocles and a Shakespeare, for the unwritten tragedies and comedies of daily life,-- was neatly and carefully dissected, its parts labeled and stowed away in their proper pigeon-holes, the inventory taken, and the whole stamped with the stamp of *un fait accompli*. Schematism was supreme, and the air of finality was over all.

We know better now. We know that that life of man whose unfolding furnishes psychology its material is the most difficult and complicated subject which man can investigate. We have some consciousness of its ramifications and of its connections. We see that man is somewhat more than a neatly dovetailed psychical machine who may be taken as an isolated individual, laid on the dissecting table of analysis and duly anatomized. We know that his life is bound up with the life of society, of the nation in the *ethos* and *nomos*; we know that he is closely connected with all the past by the lines of education, tradition, and heredity; we know that man is indeed the microcosm who has gathered into himself the riches of the world, both of space and of time, the world physical and the world psychical. We know also of the complexities of the individual life. We know that our mental life is not a syllogistic *sorites*, but an enthymeme most of whose members are suppressed; that large tracts never come into consciousness; that those which do get into consciousness, are vague and transitory, with a meaning hard to catch and read; are infinitely complex, involving traces of the entire life history of the individual, or are vicarious, having significance only in that for which they stand; that psychical life is a continuance, having no breaks into "distinct ideas which are separate existences"; that analysis is but a process of abstraction, leaving us with a parcel of parts from which the "\*geistige\*\* Band\*" is absent; that our distinctions, however necessary, are unreal and largely arbitrary; that mind is no compartment box nor bureau of departmental powers; in short, that we know almost nothing about the actual activities and processes of the soul. We know that the old psychology gave descriptions of that which has for the most part no existence, and which at the best it but described and did not explain.

I do not say this to depreciate the work of the earlier psychologists. There is no need to cast stones at those who, having a work to do, did that work well and departed. With Sir William Hamilton and J. Stuart Mill the school passed away. It is true that many psychologists still use their language and follow their respective fashions. Their influence, no doubt, is yet everywhere felt. But changed conditions are upon us, and thought, no more than revolution, goes backward. Psychology can live no better in the past than physiology or physics; but there is no more need for us to revile Hume and Reid for not giving birth to a full and complete science, than there is for complaining that Newton did not anticipate the physical knowledge of to-day, or Harvey the physiological.

The work of the earlier psychologists bore a definite and necessary relation both to the scientific conditions and the times in which it was done. If they had recognized the complexity of the subject and attempted to deal with it, the science would never have been begun. The very condition of its existence was the neglect of the largest part of the material, the seizing of a few schematic ideas and principles, and their use for universal explanation. Very mechanical and very abstract to us, no doubt, seems their division of the mind into faculties, the classification of mental phenomena into the regular, graded, clear-cut series of sensation, image, concept, etc.; but let one take a look into the actual processes of his own mind, the actual course of the mental life there revealed, and he will realize how utterly impossible were the description, much more the explanation, of what goes on there, unless the larger part of it were utterly neglected, and a few broad schematic rubrics seized by which to reduce this swimming chaos to some semblance of order.

Again, the history of all science demonstrates that much of its progress consists in bringing to light problems. Lack of consciousness of problems, even more than lack of ability to solve them, is the characteristic of the non-scientific mind. Problems cannot be solved till they are seen and stated, and the work of the earlier psychologists consisted largely in this sort of work. Further, they were filled with the *Zeitgeist* of their age, the age of the eighteenth century and the \*Aufklärung\*\*, \*which found nothing difficult, which hated mystery and complexity, which believed with all its heart in principles, the simpler and more abstract the better, and which had the passion of completion. By this spirit, the psychologists as well as the other thinkers of the day were mastered, and under its influence they thought and wrote.

Thus their work was conditioned by the nature of science itself, and by the age in which they lived. This work they did, and left to us a heritage of problems, of terminology, and of principles which we are to solve, reject, or employ as best we may. And the best we can do is to thank them, and then go about our *own* work; the worst is to make them the dividing lines of schools, or settle in hostile camps according to *their* banners. We are not called upon to defend them, for their work is in the past; we are not called upon to attack them, for *our* work is in the future.

It will be of more use briefly to notice some of the movements and tendencies which have brought about the change of attitude, and created what may be called the "New Psychology."

Not the slightest of these movements has been, of course, the reaction of the present century, from the abstract, if clear, principles of the eighteenth, towards concrete detail, even though it be confused. The general failure of the eighteenth century in all but destructive accomplishment forced the recognition of the fact that the universe is not so simple and easy a matter to deal with, after all; that there are many things in earth, to say nothing of heaven, which were not dreamed of in the philosophy of clearness and abstraction, whether that philosophy had been applied along the lines of the state, society, religion, or science. The world was sated with system and longed for fact. The age became realistic. That the movement has been accompanied with at least temporary loss in many directions, with the perishing of ideals, forgetfulness of higher purpose, decay of enthusiasm, absorption in the petty, a hard contentedness in the present, or a cynical pessimism as to both present and future, there can be no doubt. But neither may it be doubted that the movement was a necessity to bring the Antæaus of humanity back to the mother soil of experience, whence it derives its strength and very life, and to prevent it from losing itself in a substanceless vapor where its ideals and purposes become as thin and watery as the clouds towards which it aspires.

Out of this movement and as one of its best aspects came that organized, systematic, tireless study into the secrets of nature, which, counting nothing common or unclean, thought no drudgery beneath it, or rather thought nothing drudgery,-- that movement which with its results had been the great revelation given to the nineteenth century to make. In this movement psychology took its place, and in the growth of physiology which accompanied it I find the first if not the greatest occasion of the development of the New Psychology.

It is a matter in every one's knowledge that, with the increase of knowledge regarding the structure and functions of the nervous system, there has arisen a department of science known as physiological psychology, which has already thrown great light upon psychical matters. But unless I entirely misapprehend the popular opinion regarding the matter, there is very great confusion and error in this opinion, regarding the relations of this science to psychology. This opinion, if I rightly gather it, is, that physiological psychology is a science which does, or at least claims to, explain all psychical life by reference to the nature of the nervous system. To illustrate: very many professed popularizers of the results of scientific inquiry, as well as laymen, seem to think that the entire psychology of vision is explained when we have a complete knowledge of the anatomy of the retina, of its nervous connection with the brain, and of the centre in the latter which serves for visual functions; or that we know all about memory if we can discover that certain brain cells store up nervous impressions, and certain fibres serve to connect these cells,-- the latter producing the association of ideas, while the former occasion their reproduction. In short, the commonest view of physiological psychology seems to be that it is a science which shows that some or all of the events of our mental life are physically conditioned upon certain nerve-structures, and thereby *explains* these events. Nothing could be further from the truth. So far as I know, all the leading investigators clearly realize that explanations of psychical events, in order to *explain*, must themselves be psychical and not physiological. However important such knowledge as that of which we have just been speaking may be for physiology, it has *of itself* no value for psychology. It tells simply what and how physiological elements serve as a basis for psychical acts; what the latter *are*, or how they are to be explained, it tells us not at all. Physiology can no more, of itself, give us the what, why, and how of psychical life, than the physical geography of a country can enable us to construct or explain the history of the nation that has dwelt within that country. However important, however indispensable the land with all its qualities is as a basis for that history, that history itself can be ascertained and explained only through historical records and historic conditions. And so psychical events can be observed only through psychical means, and interpreted and explained by psychical conditions and facts.

What can be meant, then, by saying that the rise of this physiological psychology has produced a revolution in psychology? This: that it has given a new instrument, introduced a new *method*,-- that of experiment, which has supplemented and corrected the old method of introspection. Psychical facts still remain psychical, and are to be explained through psychical conditions; but our means of ascertaining what these facts are and how they are conditioned have been indefinitely widened. Two of the chief elements of the method of experiment are variation of conditions at the will and under the control of the experimenter, and the use of quantitative measurement. Neither of these elements can be applied through any introspective process. Both may be through physiological psychology. This starts from the well-grounded facts that the psychical events known as sensations arise through bodily stimuli, and that the psychical events known as volitions result in bodily movements; and it finds in these facts the possibility of the application of the method of experimentation. The bodily stimuli and movements may be directly controlled and measured, and thereby, indirectly, the psychical states which they excite or express.

There is no need at this day to dwell upon the advantages derived in any science from the application of experiment. We know well that it aids observation by indefinitely increasing the power of analysis and by permitting exact measurement, and that it equally aids explanation by enabling us so to vary the constituent elements of the case investigated as to select the indispensable. Nor is there need to call attention to the especial importance of experiment in a science where introspection is the only direct means of observation. We are sufficiently aware of the defects of introspection. We know that it is limited, defective, and often illusory as a means of observation, and can in no way directly explain. To explain is to mediate; to connect the given fact with an unseen principle; to refer the phenomenon to an antecedent condition,-- while introspection can deal only with the immediate present, with the given now. This is not the place to detail the specific results accomplished through this application of experiment to the psychological sphere; but two illustrations may perhaps be permitted: one from the realm of sensation, showing how it has enabled us to analyze states of consciousness which were otherwise indecomposable; and the other from that of perception, showing how it has revealed processes which could be reached through no introspective method.

It is now well known that no sensation as it exists in consciousness is simple or ultimate. Every color sensation, for example, is made up by at least three fundamental sensory \*quales\*\*, *probably those of red, green, and violet; while there is every reason to suppose that each of these qualities, far from being simple, is compounded of an indefinite number of homogeneous units. Thus the simplest musical sensation has also been experimentally proved to be in reality not simple, but doubly compound. First, there is the number of qualitatively like units constituting it which occasion the pitch of the note, according to the relations of time in which they stand to each other; and second, there is the relation which one order of these units bears to other secondary orders, which gives rise to the peculiar* timbre \*or tone-color of the sound; while in a succession of notes these relations are still further complicated by those which produce melody and harmony. And all this complexity occurs, be it remembered, in a state of consciousness which, to introspection, is homogeneous and ultimate. In these respects physiology has been to psychology what the microscope is to biology, or analysis to chemistry. But the experimental method has done more than reveal hidden parts, or analyze into simpler elements. It has aided explanation, as well as observation, by showing the processes which condition a psychical event. This is nowhere better illustrated than in visual perception. It is already almost a commonplace of knowledge that, for example, the most complex landscape which we can have before our eyes, is, psychologically speaking, not a simple ultimate fact, nor an impression stamped upon us from without, but is built up from color and muscular sensations, with, perhaps, unlocalized feelings of extension, by means of the psychical laws of interest, attention, and interpretation. It is, in short, a complex judgment involving within itself emotional, volitional, and intellectual elements. The knowledge of the nature of these elements, and of the laws which govern their combination into the complex visual scene, we owe to physiological psychology, through the new means of research with which it has endowed us. The importance of such a discovery can hardly be overestimated. In fact, this doctrine that our perceptions are not immediate facts, but are mediated psychical processes, has been called by Helmholtz the most important psychological result yet reached.

But besides the debt we owe Physiology for the method of experiment, is that which is due her for an indirect means of investigation which she has put within our hands; and it is this aspect of the case which has led, probably, to such misconceptions of the relations of the two sciences as exist. For while no direct conclusions regarding the nature of mental activities or their causes can be drawn from the character of nervous structure or function, it is possible to reason indirectly from one to the other, to draw analogies and seek confirmation. That is to say, if a certain nervous arrangement can be made out to exist, there is always a strong presumption that there is a psychical process corresponding to it; or if the connection between two physiological nerve processes can be shown to be of a certain nature, one may surmise that the relation between corresponding psychical activities is somewhat analogous. In this way, by purely physiological discoveries, the mind may be led to suspect the existence of some mental activity hitherto overlooked, and attention directed to its workings, or light may be thrown on points hitherto obscure. Thus it was, no doubt, the physiological discovery of the time occupied in transmission of a nervous impulse that led the German psychologists to their epoch-making investigations regarding the time occupied in various mental activities; thus, too, the present psychological theories regarding the relation of the intellectual and volitional tracts of minds were undoubtedly suggested and largely developed in analogy with Bell's discovery of the distinct nature of the sensory and motor nerves. Again, the present theory that memory is not a chamber hall for storing up ideas and their traces or relies, but is lines of activity along which the mind habitually works, was certainly suggested from the growing physiological belief that the brain cells which form the physical basis of memory do not in any way store up past impressions or their traces, but have, by these impressions, their structure so modified as to give rise to a certain functional mode of activity. Thus many important generalizations might be mentioned which were suggested and developed in analogy with physiological discoveries.

The influence of biological science in general upon psychology has been very great. Every important development in science contributes to the popular consciousness, and indeed to philosophy, some new conception which serves for a time as a most valuable category of classification and explanation. To biology is due the conception of organism. Traces of the notion are found long before the great rise of biological science, and, in particular, Kant has given a complete and careful exposition of it; but the great rôle which the "organic" conception has played of late is doubtless due in largest measure to the growth of biology. In psychology this conception has led to the recognition of mental life as an organic unitary process developing according to the laws of all life, and not a theatre for the exhibition of independent autonomous faculties, or a *rendezvous* in which isolated, atomic sensations and ideas may gather, hold external converse, and then forever part. Along with this recognition of the solidarity of mental life has come that of the relation in which it stands to other lives organized in society. The idea of environment is a necessity to the idea of organism, and with the conception of environment comes the impossibility of considering psychical life as an individual, isolated thing developing in a vacuum.

This idea of the organic relation of the individual to that organized social life into which he is born, from which he draws his mental and spiritual sustenance, and in which he must perform his proper function or become a mental and moral wreck, forms the transition to the other great influence which I find to have been at work in developing the New Psychology. I refer to the growth of those vast and as yet undefined topics of inquiry which may be vaguely designated as the social and historical sciences,-- the sciences of the origin and development of the various spheres of man's activity. With the development of these sciences has come the general feeling that the scope of psychology has been cabined and cramped till it has lost all real vitality, and there is now the recognition of the fact that all these sciences possess their psychological sides, present psychological material, and demand treatment and explanation at the hands of psychology. Thus the material for the latter, as well as its scope, have been indefinitely extended. Take the matter of language. What a wealth of material and of problems it offers. How did it originate; was it contemporaneous with that of thought, or did it succeed it; how have they acted and reacted upon each other; what psychological laws have been at the basis of the development and differentiation of languages, of the development of their structure and syntax, of the meaning of words, of all the rhetorical devices of language. Any one at all acquainted with modern discussions of language will recognize at a glance that the psychological presentation and discussion of such problems is almost enough of itself to revolutionize the old method of treating psychology. In the languages themselves, moreover, we have a mine of resources, which, as a record of the development of intelligence, can be compared only to the importance of the paleontological record to the student of animal and vegetable life.

But this is only one aspect, and not comparatively a large one, of the whole field. Folk-lore and primitive culture, ethnology and anthropology, all render their contributions of matter, and press upon us the necessity of explanation. The origin and development of myth, with all which it includes, the relation to the nationality, to language, to ethical ideas, to social customs, to government and the state, is itself a psychological field wider than any known to the previous century. Closely connected with this is the growth of ethical ideas, their relations to the consciousness and activities of the nation in which they originate, to practical morality, and to art. Thus I could go through the various spheres of human activity, and point out how thoroughly they are permeated with psychological questions and material. But it suffices to say that history in its broadest aspect is itself a psychological problem, offering the richest resources of matter.

Closely connected with this, and also influential in the development of the New Psychology, is that movement which may be described as the commonest thoughts of everyday life in all its forms, whether normal or abnormal. The cradle and the asylum are becoming the laboratory of the psychologist of the latter half of the nineteenth century. The study of children's minds, the discovery of their actual thoughts and feelings from babyhood up, the order and nature of the development of their mental life and the laws governing it, promises to be a mine of greatest value. When it was recognized that insanities are neither supernatural interruptions nor utterly inexplicable "visitations," it gradually became evident that they were but exaggerations of certain of the normal workings of the mind, or lack of proper harmony and co-ordination among these workings; and thus another department of inquiries, of psychical experiments performed by nature, was opened to us, which has already yielded valuable results. Even the prison and the penitentiary have made their contributions.

If there be any need of generalizing the foregoing, we may say that the development of the New Psychology has been due to the growth, on the one hand, of the science of physiology, giving us the method of experiment, and, on the other, of the sciences of humanity in general, giving us the method of objective observation, both of which indefinitely supplement and correct the old method of subjective introspection.

So much for the occasioning causes and method of the New Psychology. Are its results asked for? It will be gathered, from what has already been said, that its results cannot be put down in black and white like those of a mathematical theory. It is a movement, no system. But as a movement it has certain general features.

The chief characteristic distinguishing it from the old psychology is undoubtedly the rejection of a formal logic as its model and test. The old psychologists almost without exception held to a nominalistic logic. This of itself were a matter of no great importance, were it not for the inevitable tendency and attempt to make living concrete facts of experience square with the supposed norms of an abstract, lifeless thought, and to interpret them in accordance with its formal conceptions. This tendency has nowhere been stronger than in those who proclaimed that "experience" was the sole source of all knowledge. They emasculated experience till their logical conceptions could deal with it; they sheared it down till it would fit their logical boxes; they pruned it till it presented a trimmed tameness which would shock none of their laws; they preyed upon its vitality till it would go into the coffin of their abstractions. And neither so-called "school" was free from this tendency. The two legacies of fundamental principles which Hume left, were: that every distinct idea is a separate existence, and that every idea must be definitely determined in quantity and quality. By the first he destroyed all relation but accident; by the second he denied all universality. But these principles are framed after purely logical models; they are rather the abstract logical principles of difference and identity, of A is A and A is not B, put in the guise of a psychological expression. And the logic of concrete experience, of growth and development, repudiates such abstractions. The logic of life transcends the logic of nominalistic thought. The reaction against Hume fell back on certain ultimate, indecomposable, necessary first truths immediately known through some mysterious simple faculty of the mind. Here again the logical model manifests itself. Such intuitions are not psychological; they are conceptions bodily imported from the logical sphere. Their origin, tests, and character are all logical. But the New Psychology would not have necessary truths about principles; it would have the touch of reality in the life of the soul. It rejects the formalistic intuitionalism for one which has been well termed dynamic. It believes that truth, that reality, not necessary *beliefs about* reality, is given in the living experience of the soul's development.

Experience is realistic, not abstract. Psychical life is the fullest, deepest, and richest manifestation of this experience. The New Psychology is content to get its logic from this experience, and not do violence to the sanctity and integrity of the latter by forcing it to conform to certain preconceived abstract ideas. It wants the logic of fact, of process, of life. It has within its departments of knowledge no psycho-statics, for it can nowhere find spiritual life at rest. For this reason, it abandons all legal fiction of logical and mathematical analogies and rules; and is willing to throw itself upon experience, believing that the mother which has borne it will not betray it. But it makes no attempts to dictate to this experience, and tell it what it *must* be in order to square with a scholastic logic. Thus the New Psychology bears the realistic stamp of contact with life.

From this general characteristic result most of its features. It has already been noticed that it insists upon the unity and solidarity of psychical life against abstract theories which would break it up into atomic elements or independent powers. It lays large stress upon the will; not as an abstract power of unmotivated choice, nor as an executive power to obey the behests of the understanding, the legislative branch of the psychical government, but as a living bond connecting and conditioning *all* mental activity. It emphasizes the teleological element, not in any mechanical or external sense, but regarding life as an organism in which immanent ideas or purposes are realizing themselves through the development of experience. Thus modern psychology is intensely ethical in its tendencies. As it refuses to hypostatize abstractions into self-subsistent individuals, and as it insists upon the automatic spontaneous elements in man's life, it is making possible for the first time an adequate psychology of man's religious nature and experience. As it goes into the depths of man's nature it finds, as stone of its foundation, blood of its life, the instinctive tendencies of devotion, sacrifice, faith, and idealism which are the eternal substructure of all the struggles of the nations upon the altar stairs which slope up to God. It finds no insuperable problems in the relations of faith and reason, for it can discover in its investigations no reason which is not based upon faith, and no faith which is not rational in its origin and tendency. But to attempt to give any detailed account of these features of the New Psychology would be to go over much of the recent discussions of ethics and theology. We can conclude only by saying that, following the logic of life, it attempts to comprehend life.
